user_input=(input("please enter your name"))
user_input=(input("please enter your last name"))
user_input=(input("please enter your age"))
user_input=(input("please enter your dwelling place"))
user_input=(input("please enter your email"))