age=input("how old are you")
print(age)
born=input("what year are you born")
print(born)
study=input(" how long have you been studying?")
print(study)
busy=input("how much time a day are u busy")
print(busy)
time=input("what time is it")
print(time)
